# Generated by Django 3.0.7 on 2020-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidaturas', '0003_auto_20200716_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_cv', models.FileField(upload_to='curriculum')),
            ],
        ),
    ]
