# Generated by Django 3.1 on 2020-08-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidaturas', '0005_delete_candidatesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculums',
            fields=[
                ('id_curriculum', models.AutoField(primary_key=True, serialize=False)),
                ('id_candidato', models.IntegerField()),
                ('habilidades', models.CharField(max_length=100)),
            ],
        ),
    ]
