# Generated by Django 3.1 on 2020-08-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidaturas', '0008_auto_20200828_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculums',
            name='vaga_pontuacao',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
